#!/bin/bash

getPercentage () {
    profile=$(pacmd list-sinks | grep -A 1 "active port" | grep "active port" | awk -F'[<>]' '{print $2}' | grep headset)

    if  [[ -n $profile ]]; then
        bluezSink=$(pactl list sinks short | grep bluez | awk '{ print$2 }')
        percentage=$(pactl get-sink-volume $bluezSink | awk -F '[ /]' '/Volume:/ {print $(NF-4)}')
        dunstify "Volume" -h int:value:${percentage} -t 1500
    else
        percentage=$(pactl get-sink-volume 0 | awk -F '[ /]' '/Volume:/ {print $(NF-4)}')
        dunstify "Volume" -h int:value:${percentage} -t 1500
    fi
}

if [[ $1 == "inc" ]]; then
    profile=$(pacmd list-sinks | grep -A 1 "active port" | grep "active port" | awk -F'[<>]' '{print $2}' | grep headset)

    if  [[ -n $profile ]]; then
        bluezSink=$(pactl list sinks short | grep bluez | awk '{ print$2 }')
        pactl set-sink-volume $bluezSink +1% && getPercentage
    else
        pactl set-sink-volume 0 +1% && getPercentage
    fi
fi

if [[ $1 == "dec" ]]; then
    profile=$(pacmd list-sinks | grep -A 1 "active port" | grep "active port" | awk -F'[<>]' '{print $2}' | grep headset)

    if  [[ -n $profile ]]; then
        bluezSink=$(pactl list sinks short | grep bluez | awk '{ print$2 }')
        pactl set-sink-volume $bluezSink -1% && getPercentage
    else
        pactl set-sink-volume 0 -1% && getPercentage
    fi
fi
